name: Release Publisher

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      # Step 4: Bump the version using changesets
      - name: Version bump
        id: version_bump
        run: |
          pnpm changeset version
          NEXT_VERSION=$(pnpm pkg get version | tr -d '"')
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV

      # Step 5: Create and publish the release draft
      - name: Publish Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-config.yml

      # Step 6: Publish to GitHub
      - name: Publish to GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.NEXT_VERSION }}"
          release_name: "v${{ env.NEXT_VERSION }}"
          draft: false
          prerelease: false
