name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Build and Release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_INX_UI_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      GITHUB_TOKEN: ${{ secrets.ORG_INX_UI_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_INX_UI_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ORG_INX_UI_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Cache Turbo Build
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Configure NPM Authentication
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_INX_UI_TOKEN }}

      - name: Run Release Script
        id: changesets
        uses: changesets/action@v2
        with:
          publish: pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_INX_UI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ORG_INX_UI_TOKEN }}
