name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Build and Release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_INX_UI_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      GITHUB_TOKEN: ${{ secrets.ORG_INX_UI_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_INX_UI_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.ORG_INX_UI_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Cache Turbo Build
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Configure NPM Authentication
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_INX_UI_TOKEN }}

      - name: Build Changed Packages
        run: pnpm turbo run build --filter=...[HEAD^1]

      - name: Check for Changes
        id: changes_check
        run: |
          git fetch origin main
          git diff --quiet origin/main HEAD || echo "Changes detected."
        continue-on-error: true

      - name: Skip if No Changes
        if: ${{ failure() }}
        run: echo "No changes detected, skipping release creation."

      - name: Run Release Script
        if: ${{ success() }}
        run: pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_INX_UI_TOKEN }}
